In [ ]:
#import dependecies 
import pandas as pd 
from pathlib import Path

# Make a reference to the csv file path
csv_path = Path("Resources/ObesityDataSet_raw_and_data_sinthetic.csv")


# Import the file as a DataFrame
obesity_df = pd.read_csv(csv_path)
obesity_df.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [13]:
# Remove columns
obesity_df = obesity_df[["Age",'Gender','Height', 'Weight','FCVC', 'NCP','family_history_with_overweight','FAF','CAEC','MTRANS','NObeyesdad']]
obesity_df.head()
obesity_renamed_df = obesity_df.rename(columns={"FCVC":"Frequency of vegetable consumption",'NCP': 'Number of main meals','Family history of overweight':'Family history','FAF':'Physical activity frequency','CAEC':'Consumption of food between meals','MTRANS': 'Transportation method', 'NObeyesdad': 'Obesity level' })

In [59]:
# Rename colums 
obesity_renamed_df = obesity_df.rename(columns={'Height':'Height(in)','Weight':'Weight(lbs)', "FCVC":"Frequency of vegetable consumption",'NCP': 'Number of main meals','family_history_with_overweight':'Family history of obesity','FAF':'Physical activity frequency','CAEC':'Consumption of food between meals','MTRANS': 'Transportation method', 'NObeyesdad': 'Obesity level' })
obesity_renamed_df

,Age,Gender,Height(in),Weight(lbs),Frequency of vegetable consumption,Number of main meals,Family history of obesity,Physical activity frequency,Consumption of food between meals,Transportation method,Obesity level
0,21.000000,Female,1.620000,64.000000,2.0,3.0,yes,0.000000,Sometimes,Public_Transportation,Normal_Weight
1,21.000000,Female,1.520000,56.000000,3.0,3.0,yes,3.000000,Sometimes,Public_Transportation,Normal_Weight
2,23.000000,Male,1.800000,77.000000,2.0,3.0,yes,2.000000,Sometimes,Public_Transportation,Normal_Weight
3,27.000000,Male,1.800000,87.000000,3.0,3.0,no,2.000000,Sometimes,Walking,Overweight_Level_I
4,22.000000,Male,1.780000,89.800000,2.0,1.0,no,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,Female,1.710730,131.408528,3.0,3.0,yes,1.676269,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,Female,1.748584,133.742943,3.0,3.0,yes,1.341390,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,Female,1.752206,133.689352,3.0,3.0,yes,1.414209,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,Female,1.739450,133.346641,3.0,3.0,yes,1.139107,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,Female,1.738836,133.472641,3.0,3.0,yes,1.026452,Sometimes,Public_Transportation,Obesity_Type_III

In [60]:
# Covert colums 
obesity_renamed_df['Height(in)'] = ((obesity_renamed_df['Height(in)'] * 3.28) * 12 ).round(2)
obesity_renamed_df['Weight(lbs)'] = (obesity_renamed_df['Weight(lbs)'] * 2.204).round(2)
obesity_renamed_df

# Add BMI column
obesity_renamed_df['BMI'] = ((obesity_renamed_df['Weight(lbs)']) / ((obesity_renamed_df['Height(in)'])**2)*703)
obesity_renamed_df['BMI'] = obesity_renamed_df['BMI'].round(2)
obesity_renamed_df

# Adjust age column
obesity_renamed_df['Age'] = obesity_renamed_df['Age'].round(0)

obesity_renamed_df

,Age,Gender,Height(in),Weight(lbs),Frequency of vegetable consumption,Number of main meals,Family history of obesity,Physical activity frequency,Consumption of food between meals,Transportation method,Obesity level,BMI
0,21.0,Female,63.76,141.06,2.0,3.0,yes,0.000000,Sometimes,Public_Transportation,Normal_Weight,24.39
1,21.0,Female,59.83,123.42,3.0,3.0,yes,3.000000,Sometimes,Public_Transportation,Normal_Weight,24.24
2,23.0,Male,70.85,169.71,2.0,3.0,yes,2.000000,Sometimes,Public_Transportation,Normal_Weight,23.77
3,27.0,Male,70.85,191.75,3.0,3.0,no,2.000000,Sometimes,Walking,Overweight_Level_I,26.85
4,22.0,Male,70.06,197.92,2.0,1.0,no,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,28.35
...,...,...,...,...,...,...,...,...,...,...,...,...
2106,21.0,Female,67.33,289.62,3.0,3.0,yes,1.676269,Sometimes,Public_Transportation,Obesity_Type_III,44.91
2107,22.0,Female,68.82,294.77,3.0,3.0,yes,1.341390,Sometimes,Public_Transportation,Obesity_Type_III,43.75
2108,23.0,Female,68.97,294.65,3.0,3.0,yes,1.414209,Sometimes,Public_Transportation,Obesity_Type_III,43.55
2109,24.0,Female,68.46,293.90,3.0,3.0,yes,1.139107,Sometimes,Public_Transportation,Obesity_Type_III,44.08
2110,24.0,Female,68.44,294.17,3.0,3.0,yes,1.026452,Sometimes,Public_Transportation,Obesity_Type_III,44.15

In [62]:
# Create a for loop to change values in the columns 
for index, row in obesity_renamed_df.iterrows():
    if row['Consumption of food between meals'] == 'no':
        obesity_renamed_df.at[index,'Consumption of food between meals'] = 0
    if row['Consumption of food between meals'] == 'Sometimes':
        obesity_renamed_df.at[index,'Consumption of food between meals'] = 1
    if row['Consumption of food between meals'] == 'Frequently':
        obesity_renamed_df.at[index,'Consumption of food between meals'] = 2
    if row['Consumption of food between meals'] == 'Always':
        obesity_renamed_df.at[index,'Consumption of food between meals'] = 3

obesity_renamed_df

,Age,Gender,Height(in),Weight(lbs),Frequency of vegetable consumption,Number of main meals,Family history of obesity,Physical activity frequency,Consumption of food between meals,Transportation method,Obesity level,BMI
0,21.0,Female,63.76,141.06,2.0,3.0,yes,0.000000,1,Public_Transportation,Normal_Weight,24.39
1,21.0,Female,59.83,123.42,3.0,3.0,yes,3.000000,1,Public_Transportation,Normal_Weight,24.24
2,23.0,Male,70.85,169.71,2.0,3.0,yes,2.000000,1,Public_Transportation,Normal_Weight,23.77
3,27.0,Male,70.85,191.75,3.0,3.0,no,2.000000,1,Walking,Overweight_Level_I,26.85
4,22.0,Male,70.06,197.92,2.0,1.0,no,0.000000,1,Public_Transportation,Overweight_Level_II,28.35
...,...,...,...,...,...,...,...,...,...,...,...,...
2106,21.0,Female,67.33,289.62,3.0,3.0,yes,1.676269,1,Public_Transportation,Obesity_Type_III,44.91
2107,22.0,Female,68.82,294.77,3.0,3.0,yes,1.341390,1,Public_Transportation,Obesity_Type_III,43.75
2108,23.0,Female,68.97,294.65,3.0,3.0,yes,1.414209,1,Public_Transportation,Obesity_Type_III,43.55
2109,24.0,Female,68.46,293.90,3.0,3.0,yes,1.139107,1,Public_Transportation,Obesity_Type_III,44.08
2110,24.0,Female,68.44,294.17,3.0,3.0,yes,1.026452,1,Public_Transportation,Obesity_Type_III,44.15

In [64]:
obesity_renamed_df.loc[obesity_renamed_df['Consumption of food between meals'] == 2]

,Age,Gender,Height(in),Weight(lbs),Frequency of vegetable consumption,Number of main meals,Family history of obesity,Physical activity frequency,Consumption of food between meals,Transportation method,Obesity level,BMI
10,26.0,Male,72.82,231.42,3.000000,3.000000,yes,2.000000,2,Public_Transportation,Obesity_Type_I,30.68
11,21.0,Female,67.70,176.32,2.000000,3.000000,yes,2.000000,2,Public_Transportation,Overweight_Level_II,27.04
18,30.0,Female,67.31,180.73,3.000000,4.000000,yes,0.000000,2,Automobile,Overweight_Level_II,28.04
25,20.0,Male,62.98,110.20,2.000000,4.000000,yes,3.000000,2,Public_Transportation,Normal_Weight,19.53
26,21.0,Male,66.91,143.26,2.000000,1.000000,yes,1.000000,2,Walking,Normal_Weight,22.50
...,...,...,...,...,...,...,...,...,...,...,...,...
738,20.0,Female,63.11,99.18,3.000000,3.000000,no,1.230441,2,Public_Transportation,Insufficient_Weight,17.51
739,20.0,Female,60.43,92.57,3.000000,1.000000,no,0.000000,2,Public_Transportation,Insufficient_Weight,17.82
740,19.0,Female,60.28,92.57,2.749268,1.394539,no,0.463949,2,Public_Transportation,Insufficient_Weight,17.91
741,19.0,Female,60.05,92.57,3.000000,1.000000,no,0.000000,2,Public_Transportation,Insufficient_Weight,18.05
771,23.0,Female,67.66,167.40,2.000000,3.000000,yes,0.000000,2,Public_Transportation,Overweight_Level_I,25.71

In [67]:
duplicates_specific = obesity_renamed_df.duplicated()
print(duplicates_specific)

0       False
1       False
2       False
3       False
4       False
        ...
2106    False
2107    False
2108    False
2109    False
2110    False
Length: 2111, dtype: bool

In [68]:
obesity_renamed_df.to_csv('Resources/cleaned_obesity_dataout.csv', index=False, header=True)